title: Bak's Cat Breed Detector
description: Classify cats (and dogs) into their respective breeds 
about:
  This is a Cat Breed  Classifier using Deep Learning built on top of Pytorch.



code: https://github.com/Bakagun/BakCatBreedAI

sampleImages:
  - name: Cat Breed
    url: https://static.boredpanda.com/blog/wp-content/uploads/2020/09/cat-breeds-omg-meow-fb53-png__700.jpg
  - name: More Cat Breed
    url: https://thumbs.dreamstime.com/z/domestic-cat-breeds-hybrids-portraits-collection-isolated-white-flat-color-s-head-style-set-vector-illustration-161684480.jpg
